name: Manual

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'User name'
        required: true
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: FedericoCarboni/setup-ffmpeg@v2
      
      - run: wget -O- "https://ip.mha.fi/"

      - run: pip install -r requirements.txt
      - run: python3 main.py ${{ inputs.username }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.username }}
          path: dl/
